/**
 * Copyright 2025 David Stotijn
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/version": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the current version number of the API. */
		get: operations["getVersion"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/postal-codes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Lookup a postal code. */
		get: operations["lookupPostalCode"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/alerts/snapshot": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get alert information. */
		get: operations["getAlertsSnapshot"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/alerts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get alert information. */
		get: operations["getAlerts"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/precipitation/radar": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get precipitation radar information. */
		get: operations["getPrecipitationRadar"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/precipitation/graph": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get precipitation graph information. */
		get: operations["getPrecipitationGraph"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/seismic": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get seismic information. */
		get: operations["getSeismic"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/measurements/windspeed": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get wind speed measurements. */
		get: operations["getMeasurementsWindSpeed"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/measurements/windgusts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get wind gusts measurements. */
		get: operations["getMeasurementsWindGusts"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/measurements/temperature": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get temperature measurements. */
		get: operations["getMeasurementsTemperature"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/measurements/humidity": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get relative humidity measurements. */
		get: operations["getMeasurementsRelativeHumidity"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/weather": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get weather information. */
		get: operations["getWeather"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/weather/detail": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get detailed weather information. */
		get: operations["getWeatherDetail"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/weather/snapshot": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get weather snapshot. */
		get: operations["getWeatherSnapshot"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/subscribers/{subscriberId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Subscribe for notifications.
		 * @description Allows users to subscribe for notifications.
		 */
		put: operations["createSubscriber"];
		post?: never;
		/**
		 * Unsubscribe from notifications.
		 * @description Allows users to unsubscribe from notifications.
		 */
		delete: operations["deleteSubscriber"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/subscribers/{subscriberId}/notification-settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get notification settings.
		 * @description Retrieve the notification settings for a user.
		 */
		get: operations["getNotificationSettings"];
		/**
		 * Update notification settings.
		 * @description Update the notification settings for a user.
		 */
		put: operations["updateNotificationSettings"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		WeatherAlertsSnapshot: {
			/** @description Unique combinations of level and weatherType in the next 48 hours, code orange and yellow for heat is alert count of 2 */
			alertCount: number;
			/** @description Count of regions in which at least one alert is active in the next 48 hours */
			regionCount: number;
			/** @description Alerts per region */
			alerts: components["schemas"]["WeatherRegionAlertSnapshot"][];
			/** @description Type of weather conditions for which alerts are active */
			weatherTypes: components["schemas"]["WeatherType"][];
		};
		WeatherRegionAlertSnapshot: {
			/** @example ._1 / Drenthe */
			region: components["schemas"]["WeatherRegion"];
			/**
			 * @description The highest alert level in the region
			 * @example red
			 */
			level: components["schemas"]["WeatherAlertLevel"];
		};
		WeatherAlerts: {
			/** @description Alerts per region */
			regions: components["schemas"]["WeatherAlertsRegion"][];
			/**
			 * @description The title of the text from the metereologist
			 * @example Vandaag en morgen extreme hitte in het hele land
			 */
			title: string;
			/**
			 * @description The body of the text from the metereologist
			 * @example Vandaag en morgen wordt het tropisch warm. Daarom is het Nationaal hitteplan (RIVM) van kracht. Vanaf vanmiddag tot morgen avond geldt code oranje voor zeer hoge temperaturen, met maximumtemperaturen van 38-39°C.
			 *
			 */
			description: string;
			/** @description Alerts per region */
			alerts: components["schemas"]["WeatherRegionAlertSnapshot"][];
			/** @description Advice per alert */
			advice: components["schemas"]["WeatherAlertAdvice"][];
		};
		WeatherAlertsRegion: {
			region: components["schemas"]["WeatherRegion"];
			/** @description Alerts for this region (sorted */
			alerts: components["schemas"]["WeatherAlertExtended"][];
		};
		WeatherAlertExtended: {
			/**
			 * @description The alert level
			 * @example red
			 */
			level: components["schemas"]["WeatherAlertLevel"];
			/** @description Type of weather condition */
			weatherType: components["schemas"]["WeatherType"];
			/**
			 * @description The title of the alert
			 * @example Code oranje: hitte
			 */
			title: string;
			/**
			 * @description The description of the alert
			 * @example Code rood voor een zware storm vanavond 20:00 tot morgen 06:00.
			 */
			description: string;
		};
		WeatherAlertAdvice: {
			/**
			 * @description The alert level
			 * @example red
			 */
			level: components["schemas"]["WeatherAlertLevel"];
			/** @description Type of weather condition */
			weatherType: components["schemas"]["WeatherType"];
			/**
			 * Format: url
			 * @description The link to the Markdown formatted content of the advice used by iOS
			 * @example https://www.example.org/advies/hitte/oranje.md
			 */
			linkMd: string;
			/**
			 * Format: url
			 * @description The link to the HTML formatted content of the advice used by Android
			 * @example https://www.example.org/advies/hitte/oranje.html
			 */
			linkHtml: string;
		};
		Weather: {
			/** @description The weather backgrounds to be used. Clients should use the first background that has a dateTime in the past. */
			backgrounds?: components["schemas"]["WeatherBackground"][];
			/** @description Summary of the current weather conditions to be used. Clients should use the first summary that has a dateTime in the past. */
			summaries: components["schemas"]["WeatherSummary"][];
			/** @description Alerts for this location in the next 48 hours */
			alerts: components["schemas"]["WeatherAlert"][];
			/** @description Hourly forecast for the weather */
			hourly?: components["schemas"]["HourlyWeatherForecast"];
			/** @description Daily forecast for the weather */
			daily?: components["schemas"]["DailyWeatherForecast"];
			/** @description Sunrise and sunset times */
			sun?: components["schemas"]["SunData"];
			/** @description Wind information for the current weather */
			wind?: components["schemas"]["Wind"];
			/** @description UV index data for the current weather */
			uvIndex?: components["schemas"]["UVIndex"];
		};
		WeatherDetail: {
			/** @description Alerts for the day */
			alerts: components["schemas"]["WeatherAlertCompact"][];
			/** @description Hourly forecast to draw graphs for precipitation, temperature and wind */
			hourly?: components["schemas"]["HourlyWeatherForecast"];
			/** @description Daily forecast to draw graphs for precipitation and temperature */
			daily?: components["schemas"]["DailyWeatherGraph"];
			/** @description Precipitation information for the day */
			precipitationChance?: components["schemas"]["PrecipitationChance"];
			/** @description Sunshine information */
			sunshine?: components["schemas"]["Sunshine"];
			/** @description Wind information for the current weather */
			wind?: components["schemas"]["Wind"];
			/** @description Climate information for the current day and month */
			climate?: components["schemas"]["Climate"];
			/** @description Sunrise and sunset times */
			sun?: components["schemas"]["SunData"];
			/** @description UV index data for the current weather */
			uvIndex?: components["schemas"]["UVIndex"];
		};
		WeatherSnapshot: {
			/** @description Highest alert level currently active */
			alertLevel: components["schemas"]["WeatherAlertLevel"];
			/**
			 * @description Current temperature in degrees Celsius
			 * @example 24
			 */
			temperature?: number;
			/** @description Type of weather condition */
			weatherType: components["schemas"]["WeatherType"];
		};
		Precipitation: {
			/**
			 * Format: double
			 * @description Amount of rain in millimeter per hour
			 */
			amount: number;
			/**
			 * Format: double
			 * @description Chance of rain as a percentage
			 */
			chance: number;
		};
		PrecipitationChance: {
			/**
			 * Format: double
			 * @description Chance of rain as a percentage
			 */
			chance: number;
			/**
			 * @description Summary
			 * @example Het blijft droog
			 */
			summary: string;
		};
		PrecipitationRadar: {
			/**
			 * Format: date-time
			 * @description The time when the series of frames is generated
			 * @example 2024-02-14T07:19:00Z
			 */
			time: string;
			/** @description Precipitation Radar Frames */
			frames: components["schemas"]["PrecipitationRadarFrame"][];
		};
		PrecipitationRadarFrame: {
			/**
			 * Format: date-time
			 * @description The time of the frame
			 * @example 2024-02-14T07:19:00Z
			 */
			time: string;
			links: {
				/** Format: Link to PNG. */
				home: string;
				/** Format: Link to PNG. */
				detail: string;
			};
		};
		PrecipitationGraph: {
			/**
			 * Format: date-time
			 * @description The time when the series of frames is generated
			 * @example 2024-02-14T07:19:00Z
			 */
			time: string;
			/** @description Forecast for precipitation */
			precipitation: components["schemas"]["PrecipitationForecast"];
		};
		SunData: {
			/**
			 * Format: date-time
			 * @description The time of sunrise
			 * @example 2024-02-14T07:19:00Z
			 */
			sunrise: string;
			/**
			 * Format: date-time
			 * @description The time of sunset
			 * @example 2024-02-14T17:09:00Z
			 */
			sunset: string;
		};
		Sunshine: {
			/**
			 * @description The hours of expected sunshine
			 * @example 2
			 */
			hours?: number;
			/**
			 * @description The description of expected sunshine
			 * @example Een bewolkte dag
			 */
			description: string;
		};
		/**
		 * @description The minimum temperature in degrees Celsius
		 * @example -7
		 */
		Temperature: number;
		TemperatureRange: {
			/**
			 * Format: double
			 * @description The minimum temperature in degrees Celsius
			 * @example -7
			 */
			min?: number;
			/**
			 * Format: double
			 * @description The maximum temperature in degrees Celsius
			 * @example 24
			 */
			max?: number;
		};
		/** @example 1372 */
		WeatherType: number;
		/**
		 * @description The background sky/gradient.
		 *
		 * @enum {string}
		 */
		WeatherBackgroundSky:
			| "dayClear"
			| "dayLightCloud"
			| "dayMediumCloud"
			| "dayHeavyCloud"
			| "nightClear"
			| "nightMediumCloud"
			| "nightHeavyCloud";
		/**
		 * @description The background sun or moon.
		 *
		 * @enum {string}
		 */
		WeatherBackgroundCelestial: "sun" | "moon";
		/**
		 * @description The background clouds.
		 *
		 * @enum {string}
		 */
		WeatherBackgroundClouds:
			| "dayMist"
			| "dayLightCloud"
			| "dayMediumCloud"
			| "dayHeavyCloud"
			| "dayHeavyCloudLightning"
			| "nightMist"
			| "nightLightCloud"
			| "nightMediumCloud"
			| "nightHeavyCloud"
			| "nightHeavyCloudLightning";
		/**
		 * @description The background precipitation.
		 *
		 * @enum {string}
		 */
		WeatherBackgroundPrecipitation:
			| "lightRain"
			| "mediumRain"
			| "heavyRain"
			| "hail"
			| "lightSnow"
			| "mediumSnow"
			| "heavySnow";
		WeatherBackground: {
			/**
			 * Format: date-time
			 * @description Date of the background, the time from when this background is to be used.
			 * @example 2024-02-14T23:00:00Z
			 */
			dateTime: string;
			sky: components["schemas"]["WeatherBackgroundSky"];
			celestial?: components["schemas"]["WeatherBackgroundCelestial"];
			clouds?: components["schemas"]["WeatherBackgroundClouds"];
			precipitation?: components["schemas"]["WeatherBackgroundPrecipitation"];
		};
		Wind: {
			source: components["schemas"]["WindSource"];
			/** @description The wind speed in kilometers/hour */
			speed: number;
			/** @description The wind gusts in kilometers/hour */
			gusts: number;
			/**
			 * @description Wind source in degrees (meteorological convention, 0 degrees represents north). Only allowed nil when source is `VAR`.
			 * @example 345
			 */
			degree?: number;
			/**
			 * @description The wind speed according to the Beaufort scale
			 * @example 7
			 */
			beaufort: number;
		};
		/**
		 * @description The direction the wind is blowing from:
		 *     * `N` north wind (0° / 360°)
		 *     * `NNE` north-northeast wind (22.5°)
		 *     * `NE` northeast wind (45°)
		 *     * `ENE` east-northeast wind (67.5°)
		 *     * `E` east wind (90°)
		 *     * `ESE` east-southeast wind (112.5°)
		 *     * `SE` southeast wind (135°)
		 *     * `SSE` south-southeast wind (157.5°)
		 *     * `S` south wind (180°)
		 *     * `SSW` south-southwest wind (202.5°)
		 *     * `SW` southwest wind  (225°)
		 *     * `WSW` west-southwest wind (247.5°)
		 *     * `W` west wind (270°)
		 *     * `WNW` west-northwest wind (292.5°)
		 *     * `NW` northwest wind (315°)
		 *     * `NNW` north-northwest wind (337.5°)
		 *     * `VAR` variable wind direction
		 *
		 * @enum {string}
		 */
		WindSource:
			| "N"
			| "NNE"
			| "NE"
			| "ENE"
			| "E"
			| "ESE"
			| "SE"
			| "SSE"
			| "S"
			| "SSW"
			| "SW"
			| "WSW"
			| "W"
			| "WNW"
			| "NW"
			| "NNW"
			| "VAR";
		Climate: {
			/**
			 * @description The month for which the climate data is provided
			 * @example 2
			 */
			month: number;
			/** @description The current temperature range */
			currentTemperatureRange: components["schemas"]["TemperatureRange"];
			/** @description The historial average temperature range for the month */
			averageTemperatureRange: components["schemas"]["TemperatureRange"];
			/**
			 * @description A human-readable label for the climate data
			 * @example Gemiddeld in [begin|midden|end] februari"
			 */
			label: string;
			/**
			 * @description A human-readable summary of the climate data
			 * @example Rond 2050 is de temperatuur in de winter tussen de 0,5°C en 1,2°C hoger dan gemiddeld (1991-2020).
			 */
			summary: string;
		};
		UVIndex: {
			/**
			 * @description UV index value
			 * @example 7
			 */
			value: number;
			/**
			 * @description A human-readable of the UV index
			 * @example Ga niet langer dan 1 uur onbeschermd de zon in
			 */
			summary: string;
		};
		WeatherSummary: {
			/**
			 * Format: date-time
			 * @description Date of the summary, the time from when this summary is to be used.
			 * @example 2024-02-14T23:00:00Z
			 */
			dateTime: string;
			/**
			 * @description Current temperature in degrees Celsius
			 * @example 24
			 */
			temperature?: number;
		};
		/** @description Forecast for precipitation where each array contains the same number of items in the same order which comprise a point on the precipitation graph at a location. */
		PrecipitationForecast: {
			times: string[];
			amounts: number[];
		};
		HourlyWeatherForecast: {
			/** @description Entries with weather forecast */
			forecast: components["schemas"]["HourlyWeatherForecastEntry"][];
		};
		HourlyWeatherForecastEntry: {
			/**
			 * Format: date-time
			 * @description Date of the forecast
			 * @example 2024-02-14T23:00:00Z
			 */
			dateTime: string;
			/** @description Highest alert level active for the hour */
			alertLevel?: components["schemas"]["WeatherAlertLevel"];
			/** @description Type of weather condition */
			weatherType: components["schemas"]["WeatherType"];
			/**
			 * @description Temperature for the hour
			 * @example 24
			 */
			temperature: components["schemas"]["Temperature"];
			/** @description Precipitation information for the hour */
			precipitation: components["schemas"]["Precipitation"];
			/** @description Wind information for the hour */
			wind?: components["schemas"]["Wind"];
		};
		DailyWeatherForecast: {
			/** @description Entries with weather forecast */
			forecast: components["schemas"]["DailyWeatherForecastEntry"][];
		};
		DailyWeatherForecastEntry: {
			/**
			 * Format: date-time
			 * @description Date of the forecast
			 * @example 2024-02-14T00:00:00Z
			 */
			date: string;
			/** @description All alert levels active for the day */
			alertLevels?: components["schemas"]["WeatherAlertLevel"][];
			/** @description Type of weather condition */
			weatherType?: components["schemas"]["WeatherType"];
			/** @description Temperature range for the day */
			temperature: components["schemas"]["TemperatureRange"];
			/** @description Precipitation information for the day */
			precipitation: components["schemas"]["Precipitation"];
		};
		/** @description Graphs for precipitation and temperature with ranges (pluim) */
		DailyWeatherGraph: {
			/** @description Graph for temperature */
			temperature?: components["schemas"]["DailyTemperatureGraph"];
			/** @description Graph for precipitation */
			precipitation?: components["schemas"]["DailyPrecipitationGraph"];
		};
		/** @description Graph for temperature graph (pluim) where each array contains the same number of items in the same order which comprise points and ranges on the temperature graph. */
		DailyTemperatureGraph: {
			dates: string[];
			minTemperatures: number[];
			lowerMinTemperatures?: number[];
			upperMinTemperatures?: number[];
			maxTemperatures: number[];
			lowerMaxTemperatures?: number[];
			upperMaxTemperatures?: number[];
		};
		/** @description Graph for precipitation graph (pluim) where each array contains the same number of items in the same order which comprise a point and range on the precipitation graph. */
		DailyPrecipitationGraph: {
			dates: string[];
			amounts: number[];
			lowerAmounts?: number[];
			upperAmounts?: number[];
		};
		Location: {
			/**
			 * @description Name of the current city
			 * @example De Bilt
			 */
			city: string;
			/**
			 * @description City names are not always unique. This field contains always the province, except when the name appears more than once in a province, then it contains the council (gemeente).
			 * @example Utrecht
			 */
			disambiguator: string;
			/** @description The geographical coordinates (latitude and longitude) corresponding to the postal code. */
			geoPoint: components["schemas"]["GeoPoint"];
		};
		Version: {
			name: string;
		};
		GeoPoint: {
			/**
			 * Format: double
			 * @description The latitude coordinate of the geographical point.
			 * @example 52.1213856642
			 */
			lat: number;
			/**
			 * Format: double
			 * @description The longitude coordinate of the geographical point.
			 * @example 5.19097860256
			 */
			lon: number;
			projection: components["schemas"]["GeoPointProjection"];
		};
		/**
		 * @description Projection of the coordinates, for epsg4326 the coordinates are in WGS84 (latitude and longitude in degrees), for epsg28992 the coordinates are in RD (Rijksdriehoeksmeting) Amersfoort (latitude (y) and longitude (x) in meters)
		 * @example epsg4326
		 * @enum {string}
		 */
		GeoPointProjection: "epsg4326" | "epsg28992" | "radar";
		/** @description Location that the user has added to their home screen and is stored locally in the app */
		WeatherLocation: {
			/**
			 * @description Unique id for a city. The strings 'live' and 'transient' are reserved.
			 * @example abc123
			 */
			id: string;
			/**
			 * @description Type of the location
			 * @example city
			 */
			locationType: components["schemas"]["LocationType"];
			/**
			 * @description Name of the city or the postal code.
			 * @example De Bilt
			 */
			name: string;
			/**
			 * @description Name of the city
			 * @example De Bilt
			 */
			city: string;
			/**
			 * @description City names are not always unique. This field contains always the province, except when the name appears more than once in a province, then it contains the council (gemeente).
			 * @example Utrecht
			 */
			disambiguator: string;
			/**
			 * @description Name of the city stripped of capitals, diacritics, white space and special characters
			 * @example debilt
			 */
			search: string;
			/** @description The geographical coordinates (latitude and longitude) corresponding to the postal code. */
			geoPoint: components["schemas"]["GeoPoint"];
			/**
			 * @description Determines order of the locations.
			 * @example 0
			 */
			sort: number;
		};
		/** @enum {string} */
		LocationType: "city" | "postalCode" | "live";
		PostalCodePoint: {
			/**
			 * @description The name or locality associated with the postal code.
			 * @example De Bilt
			 */
			name: string;
			/**
			 * @description City names are not always unique. This field contains always the province, except when the name appears more than once in a province, then it contains the council (gemeente).
			 * @example Utrecht
			 */
			disambiguator: string;
			/**
			 * @description The postal code value.
			 * @example 3731
			 */
			postalCode: string;
			/** @description The geographical coordinates (latitude and longitude) corresponding to the postal code. */
			geoPoint: components["schemas"]["GeoPoint"];
		};
		/** @enum {string} */
		DeviceFamily: "ios" | "android";
		/**
		 * @description An identifier that represents the subscriber's language, in IETF BCP 47 format. This identifier typically
		 *     consists of an ISO 639-1 alpha-2 code, followed by an underscore (_), followed by an ISO 3166-1 alpha-2
		 *     value. For example, the locale code for the Netherlands is nl_NL.
		 *
		 * @default nl_NL
		 * @example nl_NL
		 */
		Locale: string;
		CreateSubscriberRequest: {
			/**
			 * @description The globally unique device token
			 * @example 00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0
			 */
			deviceToken: string;
			/**
			 * @description Type of the device being subscribed (e.g., ios or android)
			 * @example ios
			 */
			deviceFamily: components["schemas"]["DeviceFamily"];
			locale?: components["schemas"]["Locale"];
			/** @description When in debug the APNS mode will be set to sandbox (only available on non-prod envs) */
			debug?: boolean;
		};
		/**
		 * @description * `0` Heel Nederland
		 *     * `1` Drenthe
		 *     * `2` Flevoland
		 *     * `3` Friesland
		 *     * `4` Gelderland
		 *     * `5` Groningen
		 *     * `6` IJsselmeergebied
		 *     * `7` Limburg
		 *     * `8` Noord-Brabant
		 *     * `9` Noord-Holland
		 *     * `10` Overijssel
		 *     * `11` Utrecht
		 *     * `12` Waddeneilanden
		 *     * `13` Waddenzee
		 *     * `14` Zeeland
		 *     * `15` Zuid-Holland
		 *
		 * @enum {integer}
		 */
		WeatherRegion:
			| 0
			| 1
			| 2
			| 3
			| 4
			| 5
			| 6
			| 7
			| 8
			| 9
			| 10
			| 11
			| 12
			| 13
			| 14
			| 15;
		WeatherNotificationSettings: {
			/**
			 * @description The maximum level of notifications a user would like to receive
			 * @example red
			 */
			alertLevel: components["schemas"]["WeatherAlertLevel"];
			/** @example true */
			useMyLocation: boolean;
			/** @description The selected regions for which notifications should be received */
			regions: components["schemas"]["WeatherRegion"][];
		};
		WeatherAlert: {
			/**
			 * @description The alert level
			 * @example red
			 */
			level: components["schemas"]["WeatherAlertLevel"];
			/**
			 * @description The title of the alert
			 * @example Weeralarm: zware storm
			 */
			title: string;
			/**
			 * @description The description of the alert
			 * @example Code rood voor een zware storm vanavond 20:00 tot morgen 06:00.
			 */
			description: string;
		};
		WeatherAlertCompact: {
			/**
			 * @description The alert level
			 * @example red
			 */
			level: components["schemas"]["WeatherAlertLevel"];
			/**
			 * @description The description of the alert
			 * @example Code rood voor een zware storm vanavond 20:00 tot morgen 06:00.
			 */
			description: string;
		};
		/**
		 * @example red
		 * @enum {string}
		 */
		WeatherAlertLevel: "none" | "potential" | "yellow" | "orange" | "red";
		Seismic: {
			/** @description Seismic activities */
			activities: components["schemas"]["SeismicActivity"][];
		};
		SeismicActivity: {
			/** @description Unique identifier for the seismic activity */
			id: string;
			/**
			 * Format: date-time
			 * @description The time of the earthquake
			 */
			time: string;
			/** @description The geographical coordinates of the seismic activity */
			geoPoint: components["schemas"]["GeoPoint"];
			/**
			 * @description The description of the earthquake
			 * @example Er is vandaag om 14:06 bij Appingendam, Groningen een geïnduceerde aardbeving geweest, met een grootte van 0.3 op 3.0 km diepte.
			 */
			description: string;
			kind: components["schemas"]["SeismicActivityType"];
			/**
			 * Format: double
			 * @description The magnitude of the earthquake
			 */
			magnitude?: number;
			/** @description Whether the seismic activity is reviewed */
			reviewed: boolean;
			/**
			 * Format: url
			 * @description A link to the source of the seismic activity
			 * @example https://www.knmi.nl/nederland-nu/seismologie/aardbevingen/knmi2024jshd
			 */
			link: string;
		};
		/** @enum {string} */
		SeismicActivityType: "induced" | "natural" | "other";
		SeismicNotificationSettings: {
			induced: boolean;
			natural: boolean;
			unreviewed: boolean;
			other: boolean;
		};
		UserNotificationSettings: {
			weather: components["schemas"]["WeatherNotificationSettings"];
			seismic: components["schemas"]["SeismicNotificationSettings"];
		};
		ErrorResponse: {
			/**
			 * Format: int32
			 * @description The HTTP status code
			 */
			status: number;
			/** @description Human-readable error description */
			title: string;
			/** @description Auto-generated ID identifying this request */
			correlationId: string;
		};
		/**
		 * @description The unit of the measurement.
		 *
		 * @enum {string}
		 */
		MeasurementUnit:
			| "beaufort"
			| "kilometerPerHour"
			| "degreeCelsius"
			| "percentage";
		MeasurementsMap: {
			/**
			 * Format: date-time
			 * @description The time the map was generated
			 * @example 2024-02-14T07:19:00Z
			 */
			time: string;
			legend: components["schemas"]["MeasurementsLegend"];
			links: {
				/** Format: Link to PNG. */
				detail: string;
			};
		};
		/** @description Legend for the measurements map */
		MeasurementsLegend: {
			/** @description The unit of the measurements on the map */
			unit: components["schemas"]["MeasurementUnit"];
			/** @description The steps of the legend in increasing order. The colors of the first and last step are used in the bar, but won't show as a label. */
			steps: components["schemas"]["MeasurementsLegendStep"][];
		};
		/** @description Step in the legend */
		MeasurementsLegendStep: {
			/**
			 * Format: double
			 * @description The value of the step
			 * @example 1
			 */
			value: number;
			/**
			 * @description The color of the step as hex value
			 * @example #FF0000
			 */
			color: string;
		};
	};
	responses: never;
	parameters: {
		/** @description A unique user identifier, ideally a UUID >= v5 */
		SubscriberId: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getVersion: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The current version number of the API. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Version"];
				};
			};
		};
	};
	lookupPostalCode: {
		parameters: {
			query: {
				/**
				 * @description Retrieve information associated with a specific postal code. The postal code should be formatted as four
				 *     digits, or as four digits, followed by a space and two letters in capitals.
				 *
				 * @example {
				 *       "code": "3731 GA"
				 *     }
				 */
				code: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The metadata about the postal code */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PostalCodePoint"];
				};
			};
			/** @description The server cannot or will not process the request due to an apparent client error. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The requested postal code was not found. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getAlertsSnapshot: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Alerts information successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WeatherAlertsSnapshot"];
				};
			};
			/** @description Can't happen? */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getAlerts: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Alerts information successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WeatherAlerts"];
				};
			};
			/** @description Can't happen? */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getPrecipitationRadar: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Precipitation radar successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PrecipitationRadar"];
				};
			};
			/** @description Unavailable? */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getPrecipitationGraph: {
		parameters: {
			query: {
				/** @description The location for which precipitation graph information is requested.
				 *      */
				location: string;
				/** @description The date and time for which precipitation graph information is requested, which should be rounded to 5 minutes.
				 *      */
				time: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Precipitation graph successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PrecipitationGraph"];
				};
			};
			/** @description Unavailable? */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getSeismic: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Seismic information successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Seismic"];
				};
			};
			/** @description The requested location was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getMeasurementsWindSpeed: {
		parameters: {
			query: {
				/** @description The unit in which the measurements on the map and in the legend should be returned. Wind speed is measured in Beaufort.
				 *      */
				unit: components["schemas"]["MeasurementUnit"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Wind speed measurements successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeasurementsMap"];
				};
			};
			/** @description The requested information was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getMeasurementsWindGusts: {
		parameters: {
			query: {
				/** @description The unit in which the measurements on the map and in the legend should be returned. Wind gusts are measured in km/h.
				 *      */
				unit: components["schemas"]["MeasurementUnit"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Wind gusts measurements successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeasurementsMap"];
				};
			};
			/** @description The requested information was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getMeasurementsTemperature: {
		parameters: {
			query: {
				/** @description The unit in which the measurements on the map and in the legend should be returned. Temperature is measured in degrees Celcius.
				 *      */
				unit: components["schemas"]["MeasurementUnit"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Temperature measurements successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeasurementsMap"];
				};
			};
			/** @description The requested information was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getMeasurementsRelativeHumidity: {
		parameters: {
			query: {
				/** @description The unit in which the measurements on the map and in the legend should be returned. Relative humidity is measured in percentages.
				 *      */
				unit: components["schemas"]["MeasurementUnit"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Relative humidity measurements successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeasurementsMap"];
				};
			};
			/** @description The requested information was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getWeather: {
		parameters: {
			query: {
				/** @description The location for which weather information is requested.
				 *      */
				location: string;
				/** @description The region for which weather information is requested.
				 *      */
				region?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Weather information successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Weather"];
				};
			};
			/** @description The requested location was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getWeatherDetail: {
		parameters: {
			query: {
				/** @description The location for which weather information is requested.
				 *      */
				location: string;
				/** @description The region for which weather information is requested.
				 *      */
				region?: number;
				/** @description The date for which weather information is requested.
				 *      */
				date: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Weather information successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WeatherDetail"];
				};
			};
			/** @description The requested location was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getWeatherSnapshot: {
		parameters: {
			query: {
				/** @description The location for which weather information is requested.
				 *      */
				location: string;
				/** @description The region for which weather information is requested.
				 *      */
				region?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Weather snapshot successfully retrieved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WeatherSnapshot"];
				};
			};
			/** @description The requested location was not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	createSubscriber: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description A unique user identifier, ideally a UUID >= v5 */
				subscriberId: components["parameters"]["SubscriberId"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateSubscriberRequest"];
			};
		};
		responses: {
			/** @description Subscription successful */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The server cannot or will not process the request due to an apparent client error. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	deleteSubscriber: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description A unique user identifier, ideally a UUID >= v5 */
				subscriberId: components["parameters"]["SubscriberId"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Unsubscription successful */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The server cannot or will not process the request due to an apparent client error. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	getNotificationSettings: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description A unique user identifier, ideally a UUID >= v5 */
				subscriberId: components["parameters"]["SubscriberId"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response with notification settings */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserNotificationSettings"];
				};
			};
			/** @description The server cannot or will not process the request due to an apparent client error. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
	updateNotificationSettings: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description A unique user identifier, ideally a UUID >= v5 */
				subscriberId: components["parameters"]["SubscriberId"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserNotificationSettings"];
			};
		};
		responses: {
			/** @description Notification settings updated successfully */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserNotificationSettings"];
				};
			};
			/** @description The server cannot or will not process the request due to an apparent client error. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
			/** @description The server has encountered a situation it does not know how to handle. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponse"];
				};
			};
		};
	};
}
